name: Build DOC-UNIDADES

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependencias
        run: npm install
      - name: Compilar
        run: npm run build
